shared_buffers = 32GB
effective_cache_size = 80GB
work_mem = 256MB
maintenance_work_mem = 4GB
max_worker_processes = 16
max_parallel_workers = 8
max_parallel_workers_per_gather = 4
max_parallel_maintenance_workers = 4
random_page_cost = 1.1
